import { ReactNode } from 'react';
import Link from 'next/link';
import { WalletButton } from '../solana/solana-provider';

export function AppLayout({ children }: { children: ReactNode }) {
  return (
    <div
      style={{
        display: 'flex',
        flexDirection: 'column',
        minHeight: '100vh',
        background: 'radial-gradient(ellipse at 60% 40%, #23243a 0%, #090a1a 100%)',
        color: '#e0e6f6',
        fontFamily: "'Orbitron', 'Montserrat', Arial, sans-serif",
      }}
    >
      {/* Header */}
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          padding: '12px 24px',
          borderBottom: '1px solid #23243a',
          boxShadow: '0 2px 8px 0 #00ffe733',
          background: 'rgba(20, 22, 40, 0.95)',
        }}
      >
        <div style={{ display: 'flex', alignItems: 'center' }}>
          <Link href="/" style={{ display: 'flex', alignItems: 'center' }}>
            <img
              src="/solana-logo.png"
              height={32}
              alt="Solana Logo"
              style={{ marginRight: 10, filter: 'drop-shadow(0 0 8px #00ffe7)' }}
            />
            <span
              style={{
                fontWeight: 700,
                fontSize: '1.3rem',
                color: '#00ffe7',
                letterSpacing: '0.05em',
                textShadow: '0 0 8px #00ffe7',
              }}
            >
              Jupiter Swap
            </span>
          </Link>
        </div>
        <div>
          <WalletButton />
        </div>
      </div>
      {/* Main Content */}
      <div style={{ flexGrow: 1, padding: '24px', position: 'relative', zIndex: 1 }}>
        {children}
      </div>
      {/* Footer */}
      <footer
        style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          padding: '12px 24px',
          borderTop: '1px solid #23243a',
          background: 'rgba(20, 22, 40, 0.95)',
          boxShadow: '0 -2px 8px 0 #00ffe733',
        }}
      >
        <aside>
          <p style={{ color: '#8be9fd', fontSize: '0.95rem', margin: 0 }}>
            Generated by{' '}
            <a
              href="https://github.com/solana-developers/create-solana-dapp"
              target="_blank"
              rel="noopener noreferrer"
              style={{ color: '#00ffe7', textDecoration: 'underline' }}
            >
              create-solana-dapp
            </a>
          </p>
        </aside>
      </footer>
    </div>
  );
}
